import "./globals.css";
import type { Metadata } from "next";
import AuthProvider from "./util/providers/AuthContext";
import GraphQLProvider from "./util/providers/apolloProvider";
import { IsClientCtxProvider } from "./util/providers/isClientProvider";

export const metadata: Metadata = {
  title: "StudyAI",
  description: "Generated by Arky, Irha, Tiffany and Fung",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GraphQLProvider>
        <IsClientCtxProvider>
          <AuthProvider>
            <body>{children}</body>
          </AuthProvider>
        </IsClientCtxProvider>
      </GraphQLProvider>
    </html>
  );
}
