import "./globals.css";
import type { Metadata } from "next";
import Provider from "./auth/context/AuthContext";
import GraphQLProvider from "./api/utils/apolloClient";

export const metadata: Metadata = {
  title: 'StudyAI',
  description: 'Generated by Arky, Irha, Tiffany and Fung',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GraphQLProvider>
        <Provider>
          <body>{children}</body>
        </Provider>
      </GraphQLProvider>
    </html>
  );
}
